# config.yaml

input_dir: "_input"
output_dir: "_output"
model_path: "card-seg_yolo11s.pt"
log_file: "logs/app.log"
languages: [ "en" ]
# if false save the result with nearest to 16 digits response
only_16: True